name: Bug report 🐛
description: Report a bug to help us improve
labels: ['bug']
projects: Club STEAM App
title: "[🐛 Bug] Report - "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: expected-behavior-description
    attributes:
      label: "# Expected behavior ✅"
      description: | 
        What was the expected behavior?
      placeholder: |
        ## Please, provide a concise description, for example:

        The login UI was expected to give me access to home view.
    validations:
      required: true
  - type: textarea
    id: actual-behavior-description
    attributes:
      label: "# Actual behavior 🐞"
      description: | 
        What was the observed behavior?
      value: |
        ## Please, provide a concise description, for example:

        When login button was pressed, it redirected me to email validation view.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "# Steps To Reproduce 📝"
      description: Steps to reproduce the behavior.
      placeholder: |
        Please tell us how to reproduce this bug, for example:
        1. Build with '...' arguments
        2. Run with '....' arguments
        4. Use '...' configuration options
        5. See the error
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "# Screenshots / Logs 🖼️"
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Paste your screenshots here.
  - type: textarea
    id: software-info
    attributes:
      label: Software information
      description: Please provide the following information about your environment.
      placeholder:: |
        - Operating system:
        - Flutter version (`flutter doctor -v`):
        - Device version (`flutter devices`):
        - Dependencies (`flutter pub deps`):
        - Build method (`flutter run --verbose` or `flutter build <target>`):
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "# Additional context ℹ️"
      description: Do you want to share any additional context about this bug?
      placeholder: Add any other context about the problem here.
