name: Feature request ⭐ 
description: Suggest an idea or improvement for this project
labels: ['feature/request']
projects: ["Club STEAM App"]
title: "[⭐ feat] Request - "
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting this feature!  
        The more information you provide, the more likely it is that it will be picked up.
  - type: dropdown
    id: type-of-feature
    attributes:
      label: "What kind of feature do you want to suggest?"
      options:
        - New Widget
        - Improve UI 
        - Add a library
        - Refactor a method
        - DevOps stuff
      validations:
        required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: "Please, be concise when describing your new feature:"
      placeholder: | 
        A description may be:

        I suggest adding a password recovery workflow when users forget their account password.
    validations:
      required: true
  - type: textarea
    id: desired-solution
    attributes:
      label: Desired solution
      description: "Describe the solution you'd like."
      placeholder: "A clear and concise description of what you want to happen."
    validations:
      required: true
