// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgsug3pWPdGJ1h_fdkGjfYyxfvSk7Si74',
    appId: '1:941224322500:web:1112d4cc43df2abeadf091',
    messagingSenderId: '941224322500',
    projectId: 'club-steam',
    authDomain: 'club-steam.firebaseapp.com',
    storageBucket: 'club-steam.firebasestorage.app',
    measurementId: 'G-RDLLH3SPCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Dhc4nqHloJNIIk9PvHHv7g_DryzMiRk',
    appId: '1:941224322500:android:7572fe6bae0f0b31adf091',
    messagingSenderId: '941224322500',
    projectId: 'club-steam',
    storageBucket: 'club-steam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALd_ZqbYODb0NTjWH7yMUEzQxPvr4QeSY',
    appId: '1:941224322500:ios:b891a05fb1fd899cadf091',
    messagingSenderId: '941224322500',
    projectId: 'club-steam',
    storageBucket: 'club-steam.firebasestorage.app',
    iosBundleId: 'com.example.clubSteamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALd_ZqbYODb0NTjWH7yMUEzQxPvr4QeSY',
    appId: '1:941224322500:ios:b891a05fb1fd899cadf091',
    messagingSenderId: '941224322500',
    projectId: 'club-steam',
    storageBucket: 'club-steam.firebasestorage.app',
    iosBundleId: 'com.example.clubSteamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgsug3pWPdGJ1h_fdkGjfYyxfvSk7Si74',
    appId: '1:941224322500:web:8c67bc2549788a1badf091',
    messagingSenderId: '941224322500',
    projectId: 'club-steam',
    authDomain: 'club-steam.firebaseapp.com',
    storageBucket: 'club-steam.firebasestorage.app',
    measurementId: 'G-HYXDDKVGZ8',
  );
}
