// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZqT-gkot6i3D0jOnZRE-H-5p3JekhNg',
    appId: '1:24996529957:web:d83f7ab149d75276e57ccc',
    messagingSenderId: '24996529957',
    projectId: 'club-steam-abd01',
    authDomain: 'club-steam-abd01.firebaseapp.com',
    storageBucket: 'club-steam-abd01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFLkdm14ZEfH__-o1Pp5xumg-eQ8aKnLk',
    appId: '1:24996529957:android:ec4f019b328dccc9e57ccc',
    messagingSenderId: '24996529957',
    projectId: 'club-steam-abd01',
    storageBucket: 'club-steam-abd01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6tz59LoQVNqarXI-hHCai3ysnCBLr0NM',
    appId: '1:24996529957:ios:1c29210039010815e57ccc',
    messagingSenderId: '24996529957',
    projectId: 'club-steam-abd01',
    storageBucket: 'club-steam-abd01.firebasestorage.app',
    iosBundleId: 'com.example.clubSteamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6tz59LoQVNqarXI-hHCai3ysnCBLr0NM',
    appId: '1:24996529957:ios:1c29210039010815e57ccc',
    messagingSenderId: '24996529957',
    projectId: 'club-steam-abd01',
    storageBucket: 'club-steam-abd01.firebasestorage.app',
    iosBundleId: 'com.example.clubSteamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmZqT-gkot6i3D0jOnZRE-H-5p3JekhNg',
    appId: '1:24996529957:web:15c88de738a0ed5be57ccc',
    messagingSenderId: '24996529957',
    projectId: 'club-steam-abd01',
    authDomain: 'club-steam-abd01.firebaseapp.com',
    storageBucket: 'club-steam-abd01.firebasestorage.app',
  );

}